### PR TITLE
Click on individuals support

### PR DESCRIPTION
**Pull request by 06Games**
This pull request allows you to navigate in the tree by clicking on individuals or to open its page if the individual is at the root of the tree

### CODE REVIEW

**Comment by magicsunday** [comment]
Thanks for your contribution. 

For now I only picked the 820c1d3bcdd7d023b2f223bb0cd9e1c705c8ab65 commit as I'm unsure in which direction the development will lead and if clicking on the root person should lead to its individual page. Updating the chart while clicking on a person does not update the chart title, maybe this should collapse the subtree instead.

**Comment by 06Games** [comment]
Regarding the orientation of development, I see two possibilities:
- either stay on the view of a tree showing only the ancestry, and in this case, perhaps clicking on people should not change the root person
- if not, it could be to develop a real alternative to the default tree, by allowing to display the children as well as the wives. We could also think of adding an information banner when clicking on the person to have a quick overview of the information without having to open the page of the individual, a bit like what Geneanet offers (for example: [https://gw.geneanet.org/evangalli_w?n=dragon&oc=0&p=antoine&type=tree](https://gw.geneanet.org/evangalli_w?n=dragon&oc=0&p=antoine&type=tree)) In this case, I find that moving by clicking on individuals makes perfect sense and would be a real addition.

**Comment by 06Games** [comment]
Also, I would like to do another pull request to add a French translation but I did not fully understand how files with an `mo` extension open. I can open them with Notepad++ but the beginning of the file does not correspond to text. Should I use specific software or just edit the text without worrying about unrecognized characters?

**Comment by magicsunday** [comment]
I use PoEdit to edit the language files. https://poedit.net/

**Comment by magicsunday** [comment]
I added you commits but did some small changes to it.

**Pull request closed without merging**
