### PR TITLE
Fix - Allow to have multiple blocks on the same page

### PR DESCRIPTION
**Pull request by papjul**
Currently, the chart is inside a container with the same ID.
If we add multiple block charts on the same page, only one block is able to load, the others fail with "redeclaration of variable" error.

This pull request creates an unique ID for this container, to fix the issue.

### CODE REVIEW

**Comment by magicsunday** [comment]
Hi. How do you add multiple charts to a page? That doesn't mean anything to me now, but I don't know all the features of Webtrees either. Can you please provide me with a corresponding UAT that I can use to test your changes?

**Comment by papjul** [comment]
Step-by-step to reproduce the issue:
1) Disable default ancestor chart in Control Panel > All modules => This will allow blocks to default to Webtree Pedigree Chart instead
2) Customize your page. Add charts types two times.
3) Configure each block to be Pedigree, with a different person for each.
4) Only one of the two blocks will be shown at the same time on the same page due to having the same ID for each block.

It is currently hardcoded in Webtrees to be left to right layout with 3 generations. I have a pending PR that will allow more customization for this: https://github.com/fisharebest/webtrees/pull/4796

(the two PR are not dependent on each other)

**Comment by magicsunday** [comment]
Sorry. Can't find the "Charts" block.

grafik

**Comment by 06Games** [comment]
For some reason, the Chart block is only available in the home page of the tree and not in the "My page"

**Comment by papjul** [comment]
@06Games is correct, I wasn't specific enough, and didn't know that the private page didn't allow Charts blocks.

My use case is to show multiple small charts on the public page (homepage of the family). Because I have origins from different countries, I want to be able to tell the story of different branches along with a small chart each time.

Basically, my page is configured like this:
HTML
Charts
HTML
Charts
HTML
Charts
etc

**Pull request merged**
