### PR TITLE
Add default parameters for guests in a config panel

### PR DESCRIPTION
**Pull request by papjul**
Currently, default parameters are in constants.
I wanted to control it more easily from the admin, so I created this control panel.

I will let you review it and let me know if you want to integrate it, before I start working on the descendants chart the same way.

### CODE REVIEW

**Comment by magicsunday** [comment]
Hi. I'm sorry it took a while. First of all, thank you for your contribution.

I checked your changes. These do not currently work as the form configuration is already stored in the browser's LocalStorage, i.e. if you change the number of generations from the standard 4 to 6, for example, this is stored in LocalStorage. If you call up the page again, the selection of the generations is now initialized with 6. The pre-assignment from the module does not apply.

grafik

Seen in this light, an additional configuration module in the admin area doesn't really seem necessary to me.

**Comment by papjul** [comment]
This config panel was added as a default (for guests).

When you first visit the website, this would display in a specific layout with a specific number of generations.

Of course, when the user decides to change the default parameters, this becomes specific, which is the expected behavior.

I will rename the name of the pull request to clarify.

**Comment by papjul** [comment]
Is there anything else I can do to help with this feature? Thank you!

**Comment by magicsunday** [comment]
I merged it into the current branch 2.1. Sorry it took so long. Thank you for your contribution.

**Pull request closed without merging**
